services:
  beat:
    platform: linux/amd64
    image: maksonik/stream_telegram_bot:latest
    restart: always
    working_dir: /code
    env_file:
      - .env
    depends_on:
      - redis
    command: [ "celery", "-A", "scr.celery.app", "beat", "-l", "INFO" ]

  worker:
    platform: linux/amd64
    image: maksonik/stream_telegram_bot:latest
    restart: always
    working_dir: /code
    env_file:
      - .env
    depends_on:
      - redis
    command: [ "celery", "-A", "scr.celery.app", "worker", "-l", "INFO" ]

  redis:
    image: redis:7.2.7-alpine
    restart: always
    ports:
       - "6379:6379"