target-version = "py311"
src = ["."]
exclude = ["config/**"]
respect-gitignore = true
line-length = 120
indent-width = 4


[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint]
extend-select = ["E501"]


[lint.per-file-ignores]
"__init__.py" = ["F403"]
