name: Test coverage
on: [push]
jobs:
  Coverage:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.2"

      - name: Poetry lock
        run: poetry lock --no-update

      - name: Install the project dependencies
        run: poetry install

      - name: Activate venv
        run: echo "VIRTUAL_ENV=$(poetry env info --path)" >> $GITHUB_ENV

      - name: Set up environment
        run: echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

      - name: Wait for Redis to be ready
        run: |
            for i in {1..10}; do
              if nc -z localhost 6379; then
                echo "Redis is up!"
                exit 0
              fi
              echo "Waiting for Redis..."
              sleep 1
            done
            echo "Redis failed to start"
            exit 1

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
        with:
          coverageCommand: make test-cov  # make test-cov
          debug: true
